name: omicsDiagnosticsMinimal
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - pip:
      - torch
      - pulp==2.3.1
      - git+https://github.com/gagneurlab/PROTRIDER.git
