name: omicsDiagnostics

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python=3.6.8
  - pip
  - pandas==1.0.3
  - pip:
    - tensorflow==1.14.0
    - keras==1.1.0
    - wbuild


